# Generated by Django 5.0.6 on 2024-05-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_messagehandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehandler',
            name='message',
            field=models.TextField(default='Default message'),
        ),
    ]
