# Generated by Django 5.0.6 on 2024-05-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_messagehandler_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
