# Generated by Django 5.0.6 on 2024-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_whatsappsender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppSender',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
