# Generated by Django 5.0.6 on 2024-05-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_whatsappsender_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehandler',
            name='email',
            field=models.TextField(default='Default email'),
        ),
    ]
