# Generated by Django 5.0.6 on 2024-05-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_messagehandler_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehandler',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messagehandler',
            name='message',
        ),
    ]
