# Generated by Django 5.0.6 on 2024-05-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_messagehandler_email_messagehandler_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='email_address',
        ),
    ]
