# Generated by Django 5.0.6 on 2024-05-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_whatsappsender_rename_email_message_email_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Users',
        ),
    ]
